import sys


def exit_error(msg):
    print("ERROR: {}".format(msg))
    sys.exit(1)
